### ISSUE TITLE
Windows Phone 8.1 Universal APP(windows store) status API not working

### ISSUE THREAD

**Issue by nilayshah80** [neuecc/AsyncOAuth#13]
I am developing for Windows phone 8.1 using universal apps Windows store.
Able to get AccessToken after adding Portable library target to Windows phone 8.1 but status API not fetching any data and throw exception like "net_http_message_not_success_statuscode".

Code:
var client = OAuthUtility.CreateOAuthClient(key, secret accessToken);

```
        var json = await client.GetStringAsync("http://api.twitter.com/1.1/statuses/home_timeline.json?count=" + 10 + "&page=" + 1);
```

Please help.

**Comment by keiichiro1993** [comment]
http -> https
This might help you...

**Comment by nilayshah80** [comment]
aah silly mistake :)

Thanks for pointing out.
