### ISSUE TITLE
Twitter Authenticate issue.

### ISSUE THREAD

**Issue by ferpega** [neuecc/AsyncOAuth#4]
Hello,

first of all, congrats for your AsyncOAuth.  I am trying to use this to auth users on a portable client library.

I have get the 'Authorize' process and I get the AccessToken (Key and Secret).  All is fine, and even I have got the user timeline.  But...

Now I am trying to _only_ authenticate a previously already authorized user to identify him/her:
https://dev.twitter.com/docs/api/1/get/oauth/authenticate

I have tryied a lot of ways but every time I try to call it:
https://api.twitter.com/oauth/authenticate?oauth_token={0}

I get a 403-forbidden.

Any help or example will be great.

Thanks and congrats again.

**Comment by neuecc** [comment]
Thanks.

Hmn, I tried following code and it works fine.

``` csharp
// create authorizer
var authorizer = new OAuthAuthorizer(consumerKey, consumerSecret);

// get request token
var tokenResponse = await authorizer.GetRequestToken("https://api.twitter.com/oauth/request_token");
var requestToken = tokenResponse.Token;

var pinRequestUrl = authorizer.BuildAuthorizeUrl("https://api.twitter.com/oauth/authenticate", requestToken);

// browse pinRequestUrl as https://api.twitter.com/oauth/authenticate?oauth_token=****
```

Please show full code of concrete flow.

**Comment by ferpega** [comment]
Sorry, perhaps I am confused on the differences about Authorize and 
Authenticate.

I would like to Authenticate one time and Authorize always after that.

Where do you get the value of 'oauth_token' in commented line ?

// browse pinRequestUrl as https://api.twitter.com/oauth/authenticate?oauth_token=****

***\* = ?

Thanks.

**Comment by ferpega** [comment]
Ok, I see, the line:
var pinRequestUrl = authorizer.BuildAuthorizeUrl("https://api.twitter.com/oauth/authenticate", requestToken);

Creates the url with the 'oauth_token' already inside.

But when I go to GetAccessToken, the user receives a new PIN.

I am looking for automatically authenticate without a new pin.  I think I am in the wrong way, don't I ?

Regards from Spain.

**Comment by neuecc** [comment]
We have to hold an access token.
I acquire an access token once, after that I access api with it forever.

If request new access token(authorize flow, get the new pincode), former token is reseted(maybe).

**Comment by ferpega** [comment]
Ok, I have an Access_token and Access_token_secret already saved.

How can I Access to the api with that Access_token/secret ?

This is my _incomplete_ code for 'Authenticate':

``` csharp
        public async Task<AccessToken> Authenticate()
        {            
            var authorizer = GetAuthorizer(CONSUMER_KEY, CONSUMER_SECRET);

            var pinRequestUrl = authorizer.BuildAuthorizeUrl("https://api.twitter.com/oauth/authenticate", requestToken);
        }
```

And this one is my _complete_ authorize:

``` csharp
 public async Task<AccessToken> Authorize()
        {
            var authorizer = GetAuthorizer(CONSUMER_KEY, CONSUMER_SECRET);

            var tokenResponse = await authorizer.GetRequestToken("https://api.twitter.com/oauth/request_token");
            var requestToken = tokenResponse.Token;

            var accessTokenResponse = await GetAccessTokenResponse(authorizer, requestToken);

            var accessToken = accessTokenResponse.Token;
            return accessToken;
        }
```

Remember all of this code is for testing purposes.

Thanks.

**Comment by Ponf** [comment]
ferpega, hello
First you need to receive request token, after that you can build URL to authorize user:

```
    public async Task<Uri> GetLoginUrl()
    {
        var authorizer = new OAuthAuthorizer(ConsumerKey, ConsumerSecret);
        _requestToken = await authorizer.GetRequestToken("https://api.twitter.com/oauth/request_token");
       return new Uri("https://api.twitter.com/oauth/authorize?oauth_token=" + _requestToken.Token.Key);
    }
```

After it depends on your auth type. If you use PIN you need to do like in sample app. If you gahve access to browser you need to provide redirect url in your application settings on dev.twitter.com and catch you browser redirection. In redirect URL params you will get access token and token verifier. You should use them to get access token and access token secret:

```
    public async Task<TokenResponse<AccessToken>> VerifyToken(string oauthVerifier)
    {
        var token = await _authAuthorizer.GetAccessToken("https://api.twitter.com/oauth/access_token", _requestToken.Token, oauthVerifier);
        return token;
    }
```

**Comment by ferpega** [comment]
Thanks Ponf,

I think I was confused about the differences of OAuth vs OpenId.  I need OpenId and, at this momento, not OAuth, because I would like to "identify" or authenticate an user without the need of creating a new account on my system and delegating authentication on external systems.  Ala Stackoverflow but in Portable Client Libraries for Windows Store and Windows Phone.

Sorry my clutter.

Congrats for your work I am sure I'll use it sometime.
